obj-y				:= core.o
obj-$(CONFIG_SMP)		+= platsmp.o headsmp.o
obj-$(CONFIG_MACH_STM_STIH415)	+= soc-stih415.o
obj-$(CONFIG_MACH_STIH415_VELOCE)	+= board-stih415-veloce.o
obj-$(CONFIG_LOCAL_TIMERS)	+= localtimer.o
