/*
 * (c) 2010 STMicroelectronics Limited
 * Author: Stuart Menefy <stuart.menefy@st.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 */



#include <linux/init.h>
#include <linux/gpio.h>
#include <linux/delay.h>
#include <linux/platform_device.h>
#include <linux/mtd/nand.h>
#include <linux/mtd/partitions.h>
#include <linux/clk.h>
#include <linux/irq.h>
#include <linux/stm/emi.h>
#include <linux/stm/pad.h>
#include <linux/stm/device.h>
#include <linux/stm/sysconf.h>
#include <linux/stm/soc.h>
#include <linux/stm/stih415.h>
#include <linux/stm/stih415-periphs.h>

#ifdef CONFIG_ARM
#include <asm/mach/map.h>
#include <mach/soc-stih415.h>
#include <mach/hardware.h>
#endif

#ifdef CONFIG_SUPERH
#include <asm/irq-ilc.h>
#endif

#include "pio-control.h"


/* EMI resources ---------------------------------------------------------- */
/* PM support NOT TESTED */
static void stih415_emi_power(struct stm_device_state *device_state,
			      enum stm_device_power_state power)
{
	int i;
	int value = (power == stm_device_power_on) ? 0 : 1;

	stm_device_sysconf_write(device_state, "EMI_PWR", value);
	for (i = 5; i; --i) {
		if (stm_device_sysconf_read(device_state, "EMI_ACK")
		    == value)
			break;
		mdelay(10);
	}
}

static struct platform_device stih415_emi = {
	.name = "emi",
	.id = -1,
	.num_resources = 3,
	.resource = (struct resource[]) {
		STM_PLAT_RESOURCE_MEM_NAMED("emi memory", 0, 256 * 1024 * 1024),
		STM_PLAT_RESOURCE_MEM_NAMED("emi4 config", 0xfe900000, 0x874),
		STM_PLAT_RESOURCE_MEM_NAMED("emiss config", 0xfef01000, 0x80),
	},
	.dev.platform_data = &(struct stm_device_config){
		.sysconfs_num = 2,
		.sysconfs = (struct stm_device_sysconf []){
			STM_DEVICE_SYSCONF(SYSCONF(114), 0, 0, "EMI_PWR"),
			STM_DEVICE_SYSCONF(SYSCONF(187), 0, 0, "EMI_ACK"),
		},
		.power = stih415_emi_power,
	},
};

/* NAND Resources --------------------------------------------------------- */

static struct stm_plat_nand_flex_data stih415_nand_flex_data;
static struct stm_plat_nand_bch_data stih415_nand_bch_data;

static struct platform_device stih415_nandi_device = {
	.num_resources          = 3,
	.resource               = (struct resource[]) {
		STM_PLAT_RESOURCE_MEM_NAMED("nand_mem", 0xFE901000, 0x1000),
		STM_PLAT_RESOURCE_MEM_NAMED("nand_dma", 0xFEF00800, 0x0800),
		STIH415_RESOURCE_IRQ_NAMED("nand_irq", 146),
	},
};

void __init stih415_configure_nand(struct stm_nand_config *config)
{
	struct stm_plat_nand_flex_data *flex_data;
	struct stm_plat_nand_bch_data  *bch_data;

	switch (config->driver) {
	case stm_nand_emi:
		/* Not supported */
		BUG();
		break;
	case stm_nand_flex:
	case stm_nand_afm:
		/* Configure device for stm-nand-flex/afm driver */
		emiss_nandi_select(STM_NANDI_HAMMING);
		flex_data = &stih415_nand_flex_data;
		stih415_nandi_device.dev.platform_data = flex_data;
		flex_data->nr_banks = config->nr_banks;
		flex_data->banks = config->banks;
		flex_data->flex_rbn_connected = config->rbn.flex_connected;
		stih415_nandi_device.name = (config->driver == stm_nand_afm) ?
					"stm-nand-afm" : "stm-nand-flex";
		platform_device_register(&stih415_nandi_device);
		break;
	case stm_nand_bch:
		BUG_ON(config->nr_banks > 1);
		bch_data = &stih415_nand_bch_data;
		stih415_nandi_device.dev.platform_data = bch_data;
		bch_data->bank = config->banks;
		bch_data->bch_ecc_cfg = config->bch_ecc_cfg;
		stih415_nandi_device.name = "stm-nand-bch";
		platform_device_register(&stih415_nandi_device);
		break;
	default:
		BUG();
		return;
	}
}

/* SPI FSM Resources ------------------------------------------------------ */

static struct stm_pad_config stih415_spifsm_pad_config = {
	.gpios_num = 6,
	.gpios = (struct stm_pad_gpio[]) {
		STM_PAD_PIO_OUT_NAMED(12, 2, 1, "spi-fsm-clk"),
		STM_PAD_PIO_OUT_NAMED(12, 3, 1, "spi-fsm-cs"),
		/* To support QUAD mode operations, each of the following pads
		 * may be used by the IP as an input or an output.  Here we
		 * specify either PIO_OUT or PIO_IN, which sets pu = 0 && od =
		 * 0. 'oe' is taken from a signal generated by the SPI-FSM IP
		 * itself.
		 */
		STM_PAD_PIO_OUT_NAMED(12, 4, 1, "spi-fsm-mosi"),
		STM_PAD_PIO_IN_NAMED(12, 5, 1, "spi-fsm-miso"),
		STM_PAD_PIO_OUT_NAMED(12, 6, 1, "spi-fsm-hold"),
		STM_PAD_PIO_OUT_NAMED(12, 7, 1, "spi-fsm-wp"),
	}
};

static struct platform_device stih415_spifsm_device = {
	.name		= "stm-spi-fsm",
	.id		= 0,
	.num_resources	= 1,
	.resource	= (struct resource[]) {
		STM_PLAT_RESOURCE_MEM_NAMED("spi-fsm", 0xFE902000, 0x1000),
	},
};

void __init stih415_configure_spifsm(struct stm_plat_spifsm_data *data)
{
	struct sysconf_field *sc;

	stih415_spifsm_device.dev.platform_data = data;

	data->pads = &stih415_spifsm_pad_config;

	sc = sysconf_claim(SYSCONF(398), 0, 4, "mode-pins");

	/* SoC/IP Capabilities */
	data->capabilities.no_read_repeat = 1;
	data->capabilities.no_write_repeat = 1;
	data->capabilities.read_status_bug = spifsm_read_status_clkdiv4;
	data->capabilities.boot_from_spi = (sysconf_read(sc) == 0x1a) ? 1 : 0;

	sysconf_release(sc);
	platform_device_register(&stih415_spifsm_device);
}

/* ASC resources ---------------------------------------------------------- */

static struct stm_pad_config stih415_asc_pad_configs[6] = {

	/* Comms block ASCs in SASG1 */
	[0] = {
		/* UART0 */
		/* Tx: PIO10[0], Rx: PIO10[1], RTS: PIO10[3], CTS: PIO10[2] */
		/* Plus smartcard signals on PIO10[4] to PIO10[7] */
	},
	[1] = {
		/* UART1 */
		/* Tx: PIO11[0], Rx: PIO11[1], RTS: PIO11[3], CTS: PIO11[2] */
		/* Plus smartcard signals on PIO10[4] to PIO10[7] */
	},
	[2] = {
		/* UART2 */
		/* Tx: PIO17[4], Rx: PIO17[5], RTS: PIO17[7], CTS: PIO17[6] */
		.gpios_num = 4,
		.gpios = (struct stm_pad_gpio []) {
			STM_PAD_PIO_OUT(17, 4, 2),	/* TX */
			STM_PAD_PIO_IN(17, 5, 2),	/* RX */
			STM_PAD_PIO_IN_NAMED(17, 6, 2, "CTS"),
			STM_PAD_PIO_OUT_NAMED(17, 7, 2, "RTS"),
		},
	},
	[3] = {
		/* UART3 - not wired to pins */
	},

	/* SBC comms block ASCs in SASG1 */
	[4] = {
		/* SBC_UART0 (aka UART10) */
		/* Tx: PIO3[4], Rx: PIO3[5], RTS: PIO3[7], CTS: PIO3[6] */
		/* OE: PIO4[0] */
		.gpios_num = 4,
		.gpios = (struct stm_pad_gpio []) {
			STM_PAD_PIO_OUT(3, 4, 1),	/* TX */
			STM_PAD_PIO_IN(3, 5, 1),	/* RX */
			STM_PAD_PIO_IN_NAMED(3, 6, 1, "CTS"),
			STM_PAD_PIO_OUT_NAMED(3, 7, 1, "RTS"),
		},
	},
	[5] = {
		/* SBC_UART1 (aka UART11) */
		/* Tx: PIO2[6], Rx: PIO2[7], RTS: PIO3[1], CTS: PIO3[0] */
		/* OE: PIO3[2] */
		.gpios_num = 4,
		.gpios = (struct stm_pad_gpio []) {
			STM_PAD_PIO_OUT(2, 6, 3),	/* TX */
			STM_PAD_PIO_IN(2, 7, 3),	/* RX */
			STM_PAD_PIO_IN_NAMED(3, 0, 3, "CTS"),
			STM_PAD_PIO_OUT_NAMED(3, 1, 3, "RTS"),
		},
	},

#if 0
	/* MPE41 UART */
	[6] = {
		/* UART100 */
		/* Tx: PIO101[1], Rx: PIO101[2], RTS: PIO101[4], CTS: PIO101[3] */
	},
#endif
};

static struct platform_device stih415_asc_devices[] = {

	/* Comms block ASCs in SASG1 */
	/*
	 * Assuming these are UART0 to UART2 in the PIO document.
	 * Note no UART3.
	 * Assuming these are asc_100 to asc_103 in interrupt document
	 */
	[0] = {
		.name = "stm-asc",
		/* .id set in stih415_configure_asc() */
		.num_resources = 4,
		.resource = (struct resource[]) {
			STM_PLAT_RESOURCE_MEM(STIH415_ASC0_BASE, 0x2c),
			STIH415_RESOURCE_IRQ(195),
			STM_PLAT_RESOURCE_DMA_NAMED("rx_half_full", 11),
			STM_PLAT_RESOURCE_DMA_NAMED("tx_half_empty", 15),
		},
		.dev.platform_data = &(struct stm_plat_asc_data) {
			.pad_config = &stih415_asc_pad_configs[0],
			.regs = (void __iomem *)IO_ADDRESS(STIH415_ASC0_BASE),
		},
	},
	[1] = {
		.name = "stm-asc",
		/* .id set in stih415_configure_asc() */
		.num_resources = 4,
		.resource = (struct resource[]) {
			STM_PLAT_RESOURCE_MEM(STIH415_ASC1_BASE, 0x2c),
			STIH415_RESOURCE_IRQ(196),
			STM_PLAT_RESOURCE_DMA_NAMED("rx_half_full", 12),
			STM_PLAT_RESOURCE_DMA_NAMED("tx_half_empty", 16),
		},
		.dev.platform_data = &(struct stm_plat_asc_data) {
			.pad_config = &stih415_asc_pad_configs[1],
		},
	},
	[2] = {
		.name = "stm-asc",
		/* .id set in stih415_configure_asc() */
		.num_resources = 4,
		.resource = (struct resource[]) {
			STM_PLAT_RESOURCE_MEM(STIH415_ASC2_BASE, 0x2c),
			STIH415_RESOURCE_IRQ(197),
			STM_PLAT_RESOURCE_DMA_NAMED("rx_half_full", 13),
			STM_PLAT_RESOURCE_DMA_NAMED("tx_half_empty", 17),
		},
		.dev.platform_data = &(struct stm_plat_asc_data) {
			.pad_config = &stih415_asc_pad_configs[2],
		},
	},
	[3] = {
		.name = "stm-asc",
		/* .id set in stih415_configure_asc() */
		.num_resources = 4,
		.resource = (struct resource[]) {
			STM_PLAT_RESOURCE_MEM(STIH415_ASC3_BASE, 0x2c),
			STIH415_RESOURCE_IRQ(198),
			STM_PLAT_RESOURCE_DMA_NAMED("rx_half_full", 14),
			STM_PLAT_RESOURCE_DMA_NAMED("tx_half_empty", 18),
		},
		.dev.platform_data = &(struct stm_plat_asc_data) {
			.pad_config = &stih415_asc_pad_configs[3],
		},
	},

	/* SBC comms block ASCs in SASG1 */
	/*
	 * Assuming these are UART10 and UART11 in the PIO document.
	 * Assuming these are lpm_uart_0 and lpm_uart_1 in interrupt document.
	 */
	[4] = {
		.name = "stm-asc",
		/* .id set in stih415_configure_asc() */
		.num_resources = 4,
		.resource = (struct resource[]) {
			STM_PLAT_RESOURCE_MEM(STIH415_SBC_ASC0_BASE, 0x2c),
			STIH415_RESOURCE_IRQ(209),
			STM_PLAT_RESOURCE_DMA_NAMED("rx_half_full", 14),
			STM_PLAT_RESOURCE_DMA_NAMED("tx_half_empty", 18),
		},
		.dev.platform_data = &(struct stm_plat_asc_data) {
			.pad_config = &stih415_asc_pad_configs[4],
			.clk_id = "sbc_comms_clk",
		},
	},
	[5] = {
		.name = "stm-asc",
		/* .id set in stih415_configure_asc() */
		.num_resources = 4,
		.resource = (struct resource[]) {
			STM_PLAT_RESOURCE_MEM(STIH415_SBC_ASC1_BASE, 0x2c),
			STIH415_RESOURCE_IRQ(210),
			STM_PLAT_RESOURCE_DMA_NAMED("rx_half_full", 14),
			STM_PLAT_RESOURCE_DMA_NAMED("tx_half_empty", 18),
		},
		.dev.platform_data = &(struct stm_plat_asc_data) {
			.pad_config = &stih415_asc_pad_configs[5],
			.clk_id = "sbc_comms_clk",
		},
	},

	/*
	 * Note the interrupt document also describes a top level UART
	 * in the MPE41, described simply as asc_0. 
	 * Memory map describes a top level UART_0, at 0xFD4FB000.
	 */
};

/* the serial console device */
struct platform_device *stm_asc_console_device;

/* Platform devices to register */
unsigned int __initdata stm_asc_configured_devices_num = 0;
struct platform_device __initdata
		*stm_asc_configured_devices[ARRAY_SIZE(stih415_asc_devices)];

void __init stih415_configure_asc(int asc, struct stih415_asc_config *config)
{
	static int configured[ARRAY_SIZE(stih415_asc_devices)];
	static int tty_id;
	struct stih415_asc_config default_config = {};
	struct platform_device *pdev;
	struct stm_plat_asc_data *plat_data;

	BUG_ON(asc < 0 || asc >= ARRAY_SIZE(stih415_asc_devices));

	BUG_ON(configured[asc]);
	configured[asc] = 1;

	if (!config)
		config = &default_config;

	pdev = &stih415_asc_devices[asc];
	plat_data = pdev->dev.platform_data;

	pdev->id = tty_id++;
	plat_data->hw_flow_control = config->hw_flow_control;
	//plat_data->txfifo_bug = 1;
	plat_data->force_m1 = config->force_m1;

	if (!config->hw_flow_control) {
		/* Don't claim RTS/CTS pads */
		struct stm_pad_config *pad_config;
		pad_config = &stih415_asc_pad_configs[asc];
		stm_pad_set_pio_ignored(pad_config, "RTS");
		stm_pad_set_pio_ignored(pad_config, "CTS");
	}

	if (config->is_console)
		stm_asc_console_device = pdev;

	stm_asc_configured_devices[stm_asc_configured_devices_num++] = pdev;
}

/* Add platform device as configured by board specific code */
static int __init stih415_add_asc(void)
{
	return platform_add_devices(stm_asc_configured_devices,
			stm_asc_configured_devices_num);
}
arch_initcall(stih415_add_asc);



/* PIO ports resources ---------------------------------------------------- */

static int stih415_pio_pin_name(char *name, int size, int port, int pin)
{
	if (port >= 19)
		port += 100-19;
	return snprintf(name, size, "PIO%d.%d", port, pin);
}

#define STIH415_PIO_ENTRY(_num, _base)					\
	[_num] = {							\
		.name = "stm-gpio",					\
		.id = _num,						\
		.num_resources = 1,					\
		.resource = (struct resource[]) {			\
			STM_PLAT_RESOURCE_MEM(_base, 0x100),		\
		},							\
		.dev.platform_data = &(struct stm_plat_pio_data) {	\
			.regs = (void __iomem *)IO_ADDRESS(_base),	\
			.pin_name = stih415_pio_pin_name,		\
		},							\
	}

static struct platform_device stih415_pio_devices[27] = {
	/* SAS */
	/* NB the datsheet shows these starting at 0xfd611000 */
	/* 0-4: SBC_PIO */
	STIH415_PIO_ENTRY(0, 0xfe610000),
	STIH415_PIO_ENTRY(1, 0xfe611000),
	STIH415_PIO_ENTRY(2, 0xfe612000),
	STIH415_PIO_ENTRY(3, 0xfe613000),
	STIH415_PIO_ENTRY(4, 0xfe614000),
	/* 5-12: PIO_FRONT */
	STIH415_PIO_ENTRY(5, 0xfee00000),
	STIH415_PIO_ENTRY(6, 0xfee01000),
	STIH415_PIO_ENTRY(7, 0xfee02000),
	STIH415_PIO_ENTRY(8, 0xfee03000),
	STIH415_PIO_ENTRY(9, 0xfee04000),
	STIH415_PIO_ENTRY(10, 0xfee05000),
	STIH415_PIO_ENTRY(11, 0xfee06000),
	STIH415_PIO_ENTRY(12, 0xfee07000),
	/* 13-18: PIO_REAR */
	STIH415_PIO_ENTRY(13, 0xfe820000),
	STIH415_PIO_ENTRY(14, 0xfe821000),
	STIH415_PIO_ENTRY(15, 0xfe822000),
	STIH415_PIO_ENTRY(16, 0xfe823000),
	STIH415_PIO_ENTRY(17, 0xfe824000),
	STIH415_PIO_ENTRY(18, 0xfe825000),

	/* MPE */
	/* NB the data sheet has these two reversed, which is correct? */
	/* 100-102: PIO_RIGHT (aka MPE_PIO) */
	STIH415_PIO_ENTRY(19, MPE41_PIO_RIGHT_BASE + 0x0000),
	STIH415_PIO_ENTRY(20, MPE41_PIO_RIGHT_BASE + 0x1000),
	STIH415_PIO_ENTRY(21, MPE41_PIO_RIGHT_BASE + 0x2000),
	/* 103-107: PIO_LEFT (aka PIO_1_MPE) */
	STIH415_PIO_ENTRY(22, MPE41_PIO_LEFT_BASE + 0x0000),
	STIH415_PIO_ENTRY(23, MPE41_PIO_LEFT_BASE + 0x1000),
	STIH415_PIO_ENTRY(24, MPE41_PIO_LEFT_BASE + 0x2000),
	STIH415_PIO_ENTRY(25, MPE41_PIO_LEFT_BASE + 0x3000),
	STIH415_PIO_ENTRY(26, MPE41_PIO_LEFT_BASE + 0x4000),
};

static const struct stm_pio_control_retime_offset stih415_pio_retime_offset = {
	.clk1notclk0_offset	= 0,
	.delay_lsb_offset	= 2,
	.delay_msb_offset	= 3,
	.invertclk_offset	= 4,
	.retime_offset		= 5,
	.clknotdata_offset	= 6,
	.double_edge_offset	= 7,
};

static unsigned int stih415_pio_control_delays_in[] = {
	0,	/* 00: 0.0ns */
	500,	/* 01: 0.5ns */
	1000,	/* 10: 1.0ns */
	1500,	/* 11: 1.5ns */
};

static unsigned int stih415_pio_control_delays_out[] = {
	0,	/* 00: 0.0ns */
	1000,	/* 01: 1.0ns */
	2000,	/* 10: 2.0ns */
	3000,	/* 11: 3.0ns */
};

static const struct stm_pio_control_retime_params stih415_retime_params = {
	.retime_offset = &stih415_pio_retime_offset,
	.delay_times_in = stih415_pio_control_delays_in,
	.num_delay_times_in = ARRAY_SIZE(stih415_pio_control_delays_in),
	.delay_times_out = stih415_pio_control_delays_out,
	.num_delay_times_out = ARRAY_SIZE(stih415_pio_control_delays_out),
};

#define STIH415_PIO_ENTRY_CONTROL(_num, _alt_num,				\
		_oe_num, _pu_num, _od_num, _lsb, _msb,			\
		_rt)				\
	[_num] = {							\
		.alt = { SYSCONF(_alt_num) },			\
		.oe = { SYSCONF(_oe_num), _lsb, _msb },			\
		.pu = { SYSCONF(_pu_num), _lsb, _msb },			\
		.od = { SYSCONF(_od_num), _lsb, _msb },			\
		.retime_style = stm_pio_control_retime_style_packed,	\
		.retime_pin_mask = 0xff,				\
		.retime_params = &stih415_retime_params,		\
		.retiming = {						\
			{ SYSCONF(_rt) },				\
			{ SYSCONF(_rt+1) }				\
		},							\
 	}

#define STIH415_PIO_ENTRY_CONTROL4(_num, _alt_num,			\
		_oe_num, _pu_num, _od_num, _rt)			\
	STIH415_PIO_ENTRY_CONTROL(_num,   _alt_num,			\
		_oe_num, _pu_num, _od_num,  0,  7,		\
		_rt),					\
	STIH415_PIO_ENTRY_CONTROL(_num+1, _alt_num+1,		\
		_oe_num, _pu_num, _od_num,  8, 15,		\
		_rt+2),					\
	STIH415_PIO_ENTRY_CONTROL(_num+2, _alt_num+2,		\
		_oe_num, _pu_num, _od_num, 16, 23,		\
		_rt+4),					\
	STIH415_PIO_ENTRY_CONTROL(_num+3, _alt_num+3,		\
		_oe_num, _pu_num, _od_num, 24, 31,		\
		_rt+6)

static const struct stm_pio_control_config stih415_pio_control_configs[27] = {
	/*                  pio, alt,  oe,  pu,  od,lsb,msb, rt */
	/* 0-4: SBC */
	STIH415_PIO_ENTRY_CONTROL4( 0,   0,   5,   7,   9,          16),
	STIH415_PIO_ENTRY_CONTROL(  4,   4,   6,   8,  10,  0,  7,  24),
	/* 5-12: SAS_FRONT */
	STIH415_PIO_ENTRY_CONTROL4( 5, 100, 108, 110, 112,         116),
	STIH415_PIO_ENTRY_CONTROL4( 9, 104, 109, 111, 113,         124),
	/* 13-18: SAS_REAR */
	STIH415_PIO_ENTRY_CONTROL4(13, 300, 306, 308, 310,         338),
	STIH415_PIO_ENTRY_CONTROL( 17, 304, 307, 309, 311,  0,  7, 346),
	STIH415_PIO_ENTRY_CONTROL( 18, 305, 307, 309, 311,  8, 15, 348),
	/* 100-102: MPE_PIO */
	STIH415_PIO_ENTRY_CONTROL( 19, 400, 403, 404, 405,  0,  7, 406),
	STIH415_PIO_ENTRY_CONTROL( 20, 401, 403, 404, 405,  8, 15, 408),
	STIH415_PIO_ENTRY_CONTROL( 21, 402, 403, 404, 405, 16, 23, 410),
	/* 103-107: PIO_1_MPE */
	STIH415_PIO_ENTRY_CONTROL4(22, 500, 505, 507, 509,         511),
	STIH415_PIO_ENTRY_CONTROL( 26, 504, 506, 508, 510,  0,  7, 519),
};

static struct stm_pio_control stih415_pio_controls[27];

static int stih415_pio_config(unsigned gpio,
		enum stm_pad_gpio_direction direction, int function, void* priv)
{
	struct stm_pio_control_pad_config *config = priv;

	return stm_pio_control_config_all(gpio, direction, function, config,
		stih415_pio_controls,
		ARRAY_SIZE(stih415_pio_devices), 8);
}

#ifdef CONFIG_DEBUG_FS
static void stih415_pio_report(unsigned gpio, char *buf, int len)
{
	stm_pio_control_report_all(gpio, stih415_pio_controls,
		buf, len);
}
#else
#define stih415_pio_report NULL
#endif

static const struct stm_pad_ops stih415_pad_ops = {
	.gpio_config = stih415_pio_config,
	.gpio_report = stih415_pio_report,
};

static void __init stih415_pio_init(void)
{
	stm_pio_control_init(stih415_pio_control_configs, stih415_pio_controls,
			     ARRAY_SIZE(stih415_pio_control_configs));
}

static struct platform_device stih415_pio_irqmux_devices[5] = {
	{
		/* PIO0-4: SBC_PIO (aka pio_sas_sbc, PIO_SBC) */
		.name = "stm-gpio-irqmux",
		.id = 0,
		.num_resources = 2,
		.resource = (struct resource[]) {
			STM_PLAT_RESOURCE_MEM(0xfe61f080, 0x4),
			STIH415_RESOURCE_IRQ(180),
		},
		.dev.platform_data = &(struct stm_plat_pio_irqmux_data) {
			.port_first = 0,
			.ports_num = 5,
		}
	}, {
		/* PIO5-12: PIO_FRONT (aka pio_sas_front) */
		.name = "stm-gpio-irqmux",
		.id = 1,
		.num_resources = 2,
		.resource = (struct resource[]) {
			STM_PLAT_RESOURCE_MEM(0xfee0f080, 0x4),
			STIH415_RESOURCE_IRQ(181),
		},
		.dev.platform_data = &(struct stm_plat_pio_irqmux_data) {
			.port_first = 5,
			.ports_num = 8,
		}
	}, {
		/* PIO13-18: PIO_REAR (aka pio_sas_rear) */
		.name = "stm-gpio-irqmux",
		.id = 2,
		.num_resources = 2,
		.resource = (struct resource[]) {
			STM_PLAT_RESOURCE_MEM(0xfe82f080, 0x4),
			STIH415_RESOURCE_IRQ(182),
		},
		.dev.platform_data = &(struct stm_plat_pio_irqmux_data) {
			.port_first = 13,
			.ports_num = 6,
		}
	}, {
		/* PIO100-102: PIO_RIGHT (aka MPE_PIO, PIO0_MPE) */
		.name = "stm-gpio-irqmux",
		.id = 3,
		.num_resources = 2,
		.resource = (struct resource[]) {
			STM_PLAT_RESOURCE_MEM(0xfd6bf080, 0x4),
			STIH415_RESOURCE_IRQ(113),
		},
		.dev.platform_data = &(struct stm_plat_pio_irqmux_data) {
			.port_first = 19,
			.ports_num = 3,
		}
	}, {
		/* PIO103-107: PIO_LEFT (aka PIO1_MPE) */
		.name = "stm-gpio-irqmux",
		.id = 4,
		.num_resources = 2,
		.resource = (struct resource[]) {
			STM_PLAT_RESOURCE_MEM(0xfd33f080, 0x4),
			STIH415_RESOURCE_IRQ(114),
		},
		.dev.platform_data = &(struct stm_plat_pio_irqmux_data) {
			.port_first = 22,
			.ports_num = 5,
		}
	}
};

/* FDMA resources --------------------------------------------------------- */

static struct stm_plat_fdma_fw_regs stih415_fdma_fw = {
	.rev_id    = 0x10000,
	.cmd_statn = 0x10200,
	.req_ctln  = 0x10240,
	.ptrn      = 0x10800,
	.cntn      = 0x10808,
	.saddrn    = 0x1080c,
	.daddrn    = 0x10810,
	.node_size = 128,
};

static struct stm_plat_fdma_hw stih415_fdma_hw = {
	.slim_regs = {
		.id       = 0x0000 + (0x000 << 2), /* 0x0000 */
		.ver      = 0x0000 + (0x001 << 2), /* 0x0004 */
		.en       = 0x0000 + (0x002 << 2), /* 0x0008 */
		.clk_gate = 0x0000 + (0x003 << 2), /* 0x000c */
	},
	.dmem = {
		.offset = 0x10000,
		.size   = 0xc00 << 2, /* 3072 * 4 = 12K */
	},
	.periph_regs = {
		.sync_reg = 0x17f88,
		.cmd_sta  = 0x17fc0,
		.cmd_set  = 0x17fc4,
		.cmd_clr  = 0x17fc8,
		.cmd_mask = 0x17fcc,
		.int_sta  = 0x17fd0,
		.int_set  = 0x17fd4,
		.int_clr  = 0x17fd8,
		.int_mask = 0x17fdc,
	},
	.imem = {
		.offset = 0x18000,
		.size   = 0x1800 << 2, /* 6144 * 4 = 24K (18K populated) */
	},
};

static struct stm_plat_fdma_data stih415_mpe_fdma_platform_data = {
	.hw = &stih415_fdma_hw,
	.fw = &stih415_fdma_fw,
	.xbar = 0,
};

static struct platform_device stih415_mpe_fdma_devices[] = {
	{
		/* FDMA_0_MPE: */
		.name = "stm-fdma",
		.id = 0,
		.num_resources = 2,
		.resource = (struct resource[]) {
			STM_PLAT_RESOURCE_MEM(0xfd600000, 0x20000),
			STIH415_RESOURCE_IRQ(10),
		},
		.dev.platform_data = &stih415_mpe_fdma_platform_data,
	}, {
		/* FDMA_1_MPE: */
		.name = "stm-fdma",
		.id = 1,
		.num_resources = 2,
		.resource = (struct resource[2]) {
			STM_PLAT_RESOURCE_MEM(0xfd620000, 0x20000),
			STIH415_RESOURCE_IRQ(18),
		},
		.dev.platform_data = &stih415_mpe_fdma_platform_data,
	}, {
		/* FDMA_2_MPE: */
		.name = "stm-fdma",
		.id = 2,
		.num_resources = 2,
		.resource = (struct resource[2]) {
			STM_PLAT_RESOURCE_MEM(0xfd640000, 0x20000),
			STIH415_RESOURCE_IRQ(26),
		},
		.dev.platform_data = &stih415_mpe_fdma_platform_data,
	}
};

/* FDMA_MUX_MPE: 96 way */
static struct platform_device stih415_mpe_fdma_xbar_device = {
	.name = "stm-fdma-xbar",
	.id = 0,
	.num_resources = 1,
	.resource = (struct resource[]) {
		STM_PLAT_RESOURCE_MEM(0xfd6df000, 0x1000),
	},
	.dev.platform_data = &(struct stm_plat_fdma_xbar_data) {
		.first_fdma_id = 0,
		.last_fdma_id = 2,
	},
};

/* TVOUT_FDMA at 0xfe000000 ??? */

static struct stm_plat_fdma_data stih415_sas_fdma_platform_data = {
	.hw = &stih415_fdma_hw,
	.fw = &stih415_fdma_fw,
	.xbar = 1,
};

static struct platform_device stih415_sas_fdma_devices[] = {
	{
		/* FDMA_100: SAS FDMA 0 */
		.name = "stm-fdma",
		.id = 3,
		.num_resources = 2,
		.resource = (struct resource[]) {
			STM_PLAT_RESOURCE_MEM(0xfea00000, 0x20000),
			STIH415_RESOURCE_IRQ(121),
		},
		.dev.platform_data = &stih415_sas_fdma_platform_data,
	}, {
		/* FDMA_101: SAS FDMA 1 */
		.name = "stm-fdma",
		.id = 4,
		.num_resources = 2,
		.resource = (struct resource[2]) {
			STM_PLAT_RESOURCE_MEM(0xfea20000, 0x20000),
			STIH415_RESOURCE_IRQ(129),
		},
		.dev.platform_data = &stih415_sas_fdma_platform_data,
	}
};

/* FDMA_MUX_SAS: 64 way */
static struct platform_device stih415_sas_fdma_xbar_device = {
	.name = "stm-fdma-xbar",
	.id = 1,
	.num_resources = 1,
	.resource = (struct resource[]) {
		STM_PLAT_RESOURCE_MEM(0xfee61000, 0x1000),
	},
	.dev.platform_data = &(struct stm_plat_fdma_xbar_data) {
		.first_fdma_id = 3,
		.last_fdma_id = 4,
	},
};



/* sysconf resources ------------------------------------------------------ */

static int stih415_sysconf_reg_name(char *name, int size, int group, int num)
{
	if (group >= 2)
		group++;
	return snprintf(name, size, "SYSCONF%d", (group * 100) + num);
}

static struct platform_device stih415_sysconf_devices[] = {
	/* SAS */
	{
		/* CONFIG 0-33, STATUS 34-44 */
		/* SYSCFG_SBC (aka SBC_SYSCFG) */
		/* Stand-By Controler System configuration registers */
		.name		= "sysconf",
		.id		= 0,
		.num_resources	= 1,
		.resource	= (struct resource[]) {
			STM_PLAT_RESOURCE_MEM(STIH415_SBC_SYSCONF_BASE, 0xb4),
		},
		.dev.platform_data = &(struct stm_plat_sysconf_data) {
			.regs = (void __iomem *)IO_ADDRESS(STIH415_SBC_SYSCONF_BASE),
			.groups_num = 1,
			.groups = (struct stm_plat_sysconf_group []) {
				{
					.group = 0,
					.offset = 0,
					.name = "SYSCFG_SBC",
					.reg_name = stih415_sysconf_reg_name,
				}
			},
		}
	}, {
		/* CONFIG 100-185, STATUS 186-200 */
		/* SYSCFG_FRONT (aka SYSCFG_1_SAS) */
		/* SAS System configuration registers */
		.name		= "sysconf",
		.id		= 1,
		.num_resources	= 1,
		.resource	= (struct resource[]) {
			STM_PLAT_RESOURCE_MEM(STIH415_SAS_FRONT_SYSCONF_BASE, 0x194),
		},
		.dev.platform_data = &(struct stm_plat_sysconf_data) {
			.regs = (void __iomem *)IO_ADDRESS(STIH415_SAS_FRONT_SYSCONF_BASE),
			.groups_num = 1,
			.groups = (struct stm_plat_sysconf_group []) {
				{
					.group = 1,
					.offset = 0,
					.name = "SYSCFG_FRONT",
					.reg_name = stih415_sysconf_reg_name,
				}
			},
		}
	}, {
		/* SYSCONFIG 300-383, STATUS 384-399 */
		/* SYSCFG_REAR (aka SYSCFG_2_SAS) */
		/* SAS System configuration registers */
		.name		= "sysconf",
		.id		= 2,
		.num_resources	= 1,
		.resource	= (struct resource[]) {
			STM_PLAT_RESOURCE_MEM(STIH415_SAS_REAR_SYSCONF_BASE, 0x190),
		},
		.dev.platform_data = &(struct stm_plat_sysconf_data) {
			.regs = (void __iomem *)IO_ADDRESS(STIH415_SAS_REAR_SYSCONF_BASE),
			.groups_num = 1,
			.groups = (struct stm_plat_sysconf_group []) {
				{
					.group = 2,
					.offset = 0,
					.name = "SYSCFG_REAR",
					.reg_name = stih415_sysconf_reg_name,
				}
			},
		}
	},

	/* MPE */
	{
		/* SYSCONFIG 400-421, SYSSTATUS 423-429 */
		/* Note no 422, but fortunatly there is a hole in addressing */
		/* SYSCFG_LEFT (aka SYSCFG_1_MPE, SYSCFG_TRANSPORT) */
		/* MPE System configuration registers 1 */
		.name		= "sysconf",
		.id		= 3,
		.num_resources	= 1,
		.resource	= (struct resource[]) {
			STM_PLAT_RESOURCE_MEM(MPE41_LEFT_SYSCONF_BASE, 0x78),
		},
		.dev.platform_data = &(struct stm_plat_sysconf_data) {
			.regs = (void __iomem *)IO_ADDRESS(MPE41_LEFT_SYSCONF_BASE),
			.groups_num = 1,
			.groups = (struct stm_plat_sysconf_group []) {
				{
					.group = 3,
					.offset = 0,
					.name = "SYSCFG_LEFT",
					.reg_name = stih415_sysconf_reg_name,
				}
			},
		}
	}, {
		/* SYSCONFIG 500-573, SYSSTATUS 574-595 */
		/* SYSCFG_RIGHT (aka SYSCFG_0_MPE, SYSCFG_VIDEO) */
		/* MPE System configuration registers 0 */
		.name		= "sysconf",
		.id		= 4,
		.num_resources	= 1,
		.resource	= (struct resource[]) {
			STM_PLAT_RESOURCE_MEM(MPE41_RIGHT_SYSCONF_BASE, 0x180),
		},
		.dev.platform_data = &(struct stm_plat_sysconf_data) {
			.regs = (void __iomem *)IO_ADDRESS(MPE41_RIGHT_SYSCONF_BASE),
			.groups_num = 1,
			.groups = (struct stm_plat_sysconf_group []) {
				{
					.group = 4,
					.offset = 0,
					.name = "SYSCFG_RIGHT",
					.reg_name = stih415_sysconf_reg_name,
				}
			},
		}
	}, {
		/* SYSCONFIG 600-661, SYSSTATUS 662-686 */
		/* SYSCFG_SYSTEM (aka SYSCFG_3_MPE, SYSCFG_CPU) */
		/* MPE System configuration registers 3 */
		.name		= "sysconf",
		.id		= 5,
		.num_resources	= 1,
		.resource	= (struct resource[]) {
			STM_PLAT_RESOURCE_MEM(MPE41_SYSTEM_SYSCONF_BASE, 0x15c),
		},
		.dev.platform_data = &(struct stm_plat_sysconf_data) {
			.regs = (void __iomem *)IO_ADDRESS(MPE41_SYSTEM_SYSCONF_BASE),
			.groups_num = 1,
			.groups = (struct stm_plat_sysconf_group []) {
				{
					.group = 5,
					.offset = 0,
					.name = "SYSCFG_SYSTEM",
					.reg_name = stih415_sysconf_reg_name,
				}
			},
		}
	}, {
		/* LPM CONFIG and Status Registers */
		.name		= "sysconf",
		.id		= 6,
		.num_resources	= 1,
		.resource	= (struct resource[]) {
			STM_PLAT_RESOURCE_MEM(STIH415_SBC_LPM_CONF_BASE, 0x54),
		},
		.dev.platform_data = &(struct stm_plat_sysconf_data) {
			.regs = (void __iomem *)IO_ADDRESS(STIH415_SBC_LPM_CONF_BASE),
			.groups_num = 1,
			.groups = (struct stm_plat_sysconf_group []) {
				{
					.group = 6,
					.offset = 0,
					.name = "LPM_CFG_REGS",
				}
			},
		}
	},
};

/* Keyscan resources -------------------------------------------------------*/

static struct stm_pad_config stih415_keyscan_pad_config = {
	.gpios_num = 8,
	.gpios = (struct stm_pad_gpio []) {
		STM_PAD_PIO_IN(0, 2, 2),	/* KEYSCAN_IN[0] */
		STM_PAD_PIO_IN(0, 3, 2),	/* KEYSCAN_IN[1] */
		STM_PAD_PIO_IN(0, 4, 2),	/* KEYSCAN_IN[2] */
		STM_PAD_PIO_IN(2, 6, 2),	/* KEYSCAN_IN[3] */

		STM_PAD_PIO_OUT(1, 6, 2),	/* KEYSCAN_OUT[0] */
		STM_PAD_PIO_OUT(1, 7, 2),	/* KEYSCAN_OUT[1] */
		STM_PAD_PIO_OUT(0, 6, 2),	/* KEYSCAN_OUT[2] */
		STM_PAD_PIO_OUT(2, 7, 2),	/* KEYSCAN_OUT[3] */
	},
	.sysconfs_num = 1,
	.sysconfs = (struct stm_pad_sysconf []) {
		/* KEYSCAN_POWERDOWN_REQ */
		STM_PAD_SYSCONF(LPM_CONFIG(1), 8, 8, 0),
	}
};

static struct platform_device stih415_keyscan_device = {
	.name = "stm-keyscan",
	.id = -1,
	.num_resources = 2,
	.resource = (struct resource []) {
		STM_PLAT_RESOURCE_MEM(STIH415_SBC_KEYSCAN_BASE, 0x2000),
		STIH415_RESOURCE_IRQ(212),
	},
	.dev.platform_data = &(struct stm_plat_keyscan_data) {
		.pad_config = &stih415_keyscan_pad_config,
	},
};

void stih415_configure_keyscan(const struct stm_keyscan_config *config)
{
	struct stm_plat_keyscan_data *plat_data;
	int i;

	plat_data = stih415_keyscan_device.dev.platform_data;
	plat_data->keyscan_config = *config;	/* struct copy */

	for (i = config->num_in_pads; i < 4; i++)
		stih415_keyscan_pad_config.gpios[i].direction =
			stm_pad_gpio_direction_ignored;
	for (i = config->num_out_pads+4; i < 8; i++)
		stih415_keyscan_pad_config.gpios[i].direction =
			stm_pad_gpio_direction_ignored;

	clk_add_alias_platform_device(NULL, &stih415_keyscan_device,
				      "sbc_comms_clk", NULL);

	platform_device_register(&stih415_keyscan_device);
}


/* Utility functions  ------------------------------------------------------*/

void stih415_reset(char mode, const char *cmd)
{
	struct sysconf_field *sc = sysconf_claim(SYSCONF(11),
							0, 0, "LPM_SW_RST_N");
	sysconf_write(sc, 0);
}

/* Early initialisation-----------------------------------------------------*/

/* Initialise devices which are required early in the boot process. */
void __init stih415_early_device_init(void)
{
	struct sysconf_field *sc;

	/* Initialise PIO and sysconf drivers */
	sysconf_early_init(stih415_sysconf_devices,
			   ARRAY_SIZE(stih415_sysconf_devices));
	stih415_pio_init();
	stm_gpio_early_init(stih415_pio_devices,
			ARRAY_SIZE(stih415_pio_devices),
#ifdef CONFIG_ARM
			256
#else
			ILC_FIRST_IRQ + ILC_NR_IRQS 
#endif
		);
	stm_pad_init(ARRAY_SIZE(stih415_pio_devices) * STM_GPIO_PINS_PER_PORT,
		     0, 0, &stih415_pad_ops);

	sc = sysconf_claim(SYSCONF(427), 0, 31, "devid");
	stm_soc_set(sysconf_read(sc), -1, -1);
}



/* Pre-arch initialisation ------------------------------------------------ */

static int __init stih415_postcore_setup(void)
{
	int i;

	for (i = 0; i < ARRAY_SIZE(stih415_pio_devices); i++)
		platform_device_register(&stih415_pio_devices[i]);
	for (i = 0; i < ARRAY_SIZE(stih415_pio_irqmux_devices); i++)
		platform_device_register(&stih415_pio_irqmux_devices[i]);

	return platform_device_register(&stih415_emi);
}
postcore_initcall(stih415_postcore_setup);



/* Internal temperature sensor resources ---------------------------------- */
static void stih415_temp_power(struct stm_device_state *device_state,
		enum stm_device_power_state power)
{
	int value = (power == stm_device_power_on) ? 1 : 0;

	stm_device_sysconf_write(device_state, "TEMP_PWR", value);
}

static struct platform_device stih415_temp_device[] = {
	[0] = {
		/* Thermal sensor on SAS */
		.name = "stm-temp",
		.id = 0,
		.dev.platform_data = &(struct plat_stm_temp_data) {
			.dcorrect = { SYSCONF(178), 4, 8 },
			.overflow = { SYSCONF(198), 8, 8 },
			.data = { SYSCONF(198), 10, 16 },
			.device_config = &(struct stm_device_config) {
				.sysconfs_num = 1,
				.power = stih415_temp_power,
				.sysconfs = (struct stm_device_sysconf []){
					STM_DEVICE_SYSCONF(SYSCONF(178),
						9, 9, "TEMP_PWR"),
				},
			}
		},
	},
	[1] = {
		/* Thermal sensor on MPE */
		.name = "stm-temp",
		.id = 1,
		.dev.platform_data = &(struct plat_stm_temp_data) {
			.dcorrect = { SYSCONF(607), 3, 7 },
			.overflow = { SYSCONF(667), 9, 9 },
			.data = { SYSCONF(667), 11, 18 },
			.device_config = &(struct stm_device_config) {
				.sysconfs_num = 1,
				.power = stih415_temp_power,
				.sysconfs = (struct stm_device_sysconf []){
					STM_DEVICE_SYSCONF(SYSCONF(607),
						8, 8, "TEMP_PWR"),
				},
			}
		},
	}

};

/* Hardware RNG driver */

static struct platform_device stih415_devhwrandom_device = {
	.name           = "stm-hwrandom",
	.id             = -1,
	.num_resources  = 1,
	.resource       = (struct resource []) {
		STM_PLAT_RESOURCE_MEM(0xfd6d8000, 0x1000),
	}
};

/* Low Power Controller ---------------------------------------------------- */

static struct platform_device stih415_lpc_device = {
	.name	= "stm-rtc",
	.id	= -1,
	.num_resources = 2,
	.resource = (struct resource[]){
		STM_PLAT_RESOURCE_MEM(0xfde05000, 0x1000),
		STIH415_RESOURCE_IRQ(118),
	},
	.dev.platform_data = &(struct stm_plat_rtc_lpc) {
		.need_wdt_reset = 1,
#ifdef CONFIG_ARM
		.irq_edge_level = IRQ_TYPE_EDGE_RISING,
#else
		.irq_edge_level = IRQ_TYPE_EDGE_FALLING,
#endif
		/*
		 * the lpc_clk is initialize @ 300 KHz to guarantee
		 * it's working also for the temperature sensor
		 */
		.force_clk_rate = 300000,
	}
};

/* System Trace Module resources------------------------------------------- */

static struct stm_pad_config stih415_systrace_pad_config = {
	.gpios_num = 5,
	.gpios = (struct stm_pad_gpio[]){
		 STM_PAD_PIO_OUT(20, 3, 4),	/* DATA0 */
		 STM_PAD_PIO_OUT(20, 4, 4),	/* DATA1 */
		 STM_PAD_PIO_OUT(20, 5, 4),	/* DATA2 */
		 STM_PAD_PIO_OUT(20, 6, 4),	/* DATA3 */
		 STM_PAD_PIO_OUT(20, 7, 4),	/* BCLK */
		 },
};

static struct platform_device stih415_systrace_device = {
	.name = "stm-systrace",
	.id = 0,
	.num_resources = 2,
	.resource = (struct resource[]){
		/* 8k (4k for each A9 initiator) */
		STM_PLAT_RESOURCE_MEM(STIH415_SYSTRACE_BASE, 0x2000),
		STM_PLAT_RESOURCE_MEM(STIH415_SYSTRACE_REGS, 0x1000),
		},
	.dev.platform_data = &(struct stm_plat_systrace_data) {
		.pad_config = &stih415_systrace_pad_config,
	},
};

static int __init stih415_setup_systrace(void)
{
	return platform_device_register(&stih415_systrace_device);
}
device_initcall(stih415_setup_systrace);

/* Late initialisation ---------------------------------------------------- */

static struct platform_device *stih415_devices[] __initdata = {
	&stih415_mpe_fdma_devices[0],
	&stih415_mpe_fdma_devices[1],
	&stih415_mpe_fdma_devices[2],
	&stih415_mpe_fdma_xbar_device,
	&stih415_sas_fdma_devices[0],
	&stih415_sas_fdma_devices[1],
	&stih415_sas_fdma_xbar_device,
	&stih415_temp_device[0],
	&stih415_temp_device[1],
	&stih415_devhwrandom_device,
	&stih415_lpc_device,
};

static int __init stih415_devices_setup(void)
{
	return platform_add_devices(stih415_devices,
			ARRAY_SIZE(stih415_devices));
}
device_initcall(stih415_devices_setup);
