#
# Makefile for the Linux/SuperH CPU-specifc IRQ handlers.
#
obj-$(CONFIG_SUPERH32)			+= imask.o
obj-$(CONFIG_CPU_SH5)			+= intc-sh5.o
obj-$(CONFIG_CPU_HAS_IPR_IRQ)		+= ipr.o
obj-$(CONFIG_CPU_SUBTYPE_STIH415)	+= ilc3.o
obj-$(CONFIG_CPU_SUBTYPE_STXH205)	+= ilc3.o
obj-$(CONFIG_CPU_SUBTYPE_STX7108)	+= ilc3.o
