/*
 *  Copyright (C) 2013 STMicroelectronics
 *  Author: Youssef Triki <youssef.triki@st.com>
 *  Author: Giuseppe Cavallaro <peppe.cavallaro@st.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or (at
 * your option) any later version.
 */

#ifndef __DRIVERS_STM_STIH407_SDHCI_H
#define __DRIVERS_STM_STIH407_SDHCI_H

#define	 FLASHSS_MMC_CORE_CONFIG_1			0x400
#define  FLASHSS_MMC_CORECFG_TIMEOUT_CLK_UNIT	24
#define   FLASHSS_MMC_CORECFG_TIMEOUT_CLK_UNIT_MHZ	1
#define   FLASHSS_MMC_CORECFG_TIMEOUT_CLK_UNIT_KHZ	0

#define  FLASHSS_MMC_CORECFG_TIMEOUT_CLK_FREQ	12
#define   FLASHSS_MMC_CORECFG_TIMEOUT_CLK_FREQ_MIN	1
#define   FLASHSS_MMC_CORECFG_TIMEOUT_CLK_FREQ_MAX	0x3F	/*63 */

#define  FLASHSS_MMC_CORECFG_TUNING_COUNT		4
#define   FLASHSS_MMC_CORECFG_TUNING_COUNT_MAX	0x10	/*16 */
#define   FLASHSS_MMC_CORECFG_TUNING_COUNT_MIN	0	/*1 */

#define  FLASHSS_MMC_CORECFG_ASYNC_WAKEUP_EN	0
#define   FLASHSS_MMC_CORECFG_SYNC_WAKEUP		0
#define   FLASHSS_MMC_CORECFG_ASYNC_WAKEUP		1

#define STM_FLASHSS_MMC_CORE_CONFIG_1	\
			((FLASHSS_MMC_CORECFG_TIMEOUT_CLK_UNIT_MHZ << 24) | \
			(FLASHSS_MMC_CORECFG_TIMEOUT_CLK_FREQ_MIN << 12) | \
			(FLASHSS_MMC_CORECFG_TUNING_COUNT_MAX << 4) |\
			(FLASHSS_MMC_CORECFG_SYNC_WAKEUP << 0))

#define FLASHSS_MMC_CORE_CONFIG_2			0x404

#define  FLASHSS_MMC_CORECFG_HIGH_SPEED_SUPPORT		28
#define   FLASHSS_MMC_CORECFG_HIGH_SPEED		1
#define   FLASHSS_MMC_CORECFG_NORMAL_SPEED		0

#define  FLASHSS_MMC_CORECFG_ADMA2_SUPPORT		24
#define   FLASHSS_MMC_CORECFG_ADMA2			1
#define   FLASHSS_MMC_CORECFG_NO_ADMA2		0

#define  FLASHSS_MMC_CORECFG_8BIT_SUPPORT		20
#define   FLASHSS_MMC_CORECFG_8BIT_EMMC		1
#define   FLASHSS_MMC_CORECFG_4BIT_SD		0

#define  FLASHSS_MMC_CORECFG_MAX_BLK_LENGTH		16
#define   MAX_BLK_LENGTH_512		0
#define   MAX_BLK_LENGTH_1024		1
#define   MAX_BLK_LENGTH_2048		2

#define FLASHSS_MMC_CORECFG_BASE_CLK_FREQ		0
#define BASE_CLK_FREQ_200		0xc8
#define BASE_CLK_FREQ_MIN		0x1
#define BASE_CLK_FREQ_MAX		0xff

#define STM_FLASHSS_MMC_CORE_CONFIG_2	\
				((FLASHSS_MMC_CORECFG_HIGH_SPEED << 28) | \
				 (FLASHSS_MMC_CORECFG_ADMA2 << 24) | \
				 (FLASHSS_MMC_CORECFG_8BIT_EMMC << 20) | \
				 (MAX_BLK_LENGTH_1024 << 16) | \
				 (BASE_CLK_FREQ_200 << 0))

#define FLASHSS_MMC_CORE_CONFIG_3			0x408

#define FLASHSS_MMC_CORECFG_SLOT_TYPE		28
#define  FLASHSS_MMC_CORECFG_SLOT_TYPE_SD		0
#define  FLASHSS_MMC_CORECFG_SLOT_TYPE_EMMC		1
#define  FLASHSS_MMC_CORECFG_SLOT_TYPE_SHARED	2

#define FLASHSS_MMC_CORECFG_64BIT_BUS_SUPPORT	24
#define  FLASHSS_MMC_CORECFG_64BIT			1
#define  FLASHSS_MMC_CORECFG_32BIT			0

#define FLASHSS_MMC_CORECFG_ASYNCH_INTR_SUPPORT	(1 << 20)

#define FLASHSS_MMC_CORECFG_1P8_VOLT_SUPPORT	16
#define FLASHSS_MMC_CORECFG_1P8_VOLT		1
#define FLASHSS_MMC_CORECFG_NO_1P8_VOLT		0

#define FLASHSS_MMC_CORECFG_3P0_VOLT_SUPPORT	12
#define FLASHSS_MMC_CORECFG_3P0_VOLT		1
#define FLASHSS_MMC_CORECFG_NO_3P0_VOLT		0

#define FLASHSS_MMC_CORECFG_3P3_VOLT_SUPPORT	8
#define FLASHSS_MMC_CORECFG_3P3_VOLT		1
#define FLASHSS_MMC_CORECFG_NO_3P3_VOLT		0

#define FLASHSS_MMC_CORECFG_SUSP_RES_SUPPORT	(1 << 4)

#define FLASHSS_MMC_CORECFG_SDMA_SUPPORT	0
#define FLASHSS_MMC_CORECFG_SDMA		1
#define FLASHSS_MMC_CORECFG_NO_SDMA		0

#define STM_FLASHSS_MMC_CORE_CONFIG_3	\
			((FLASHSS_MMC_CORECFG_SLOT_TYPE_EMMC << 28)	| \
			 (FLASHSS_MMC_CORECFG_32BIT << 24)		| \
			 (FLASHSS_MMC_CORECFG_ASYNCH_INTR_SUPPORT)	| \
			 (FLASHSS_MMC_CORECFG_1P8_VOLT<<16)		| \
			 (FLASHSS_MMC_CORECFG_NO_3P0_VOLT << 12)	| \
			 (FLASHSS_MMC_CORECFG_3P3_VOLT << 8)	| \
			 (FLASHSS_MMC_CORECFG_SUSP_RES_SUPPORT)	| \
			 (FLASHSS_MMC_CORECFG_SDMA << 0))

#define FLASHSS_MMC_CORE_CONFIG_4			0xc
#define FLASHSS_MMC_CORECFG_D_DRIVER_SUPPORT	(1 << 20)
#define FLASHSS_MMC_CORECFG_C_DRIVER_SUPPORT	(1 << 16)
#define FLASHSS_MMC_CORECFG_A_DRIVER_SUPPORT	(1 << 12)
#define FLASHSS_MMC_CORECFG_DDR50_SUPPORT		8
#define  FLASHSS_MMC_CORECFG_DDR50			1
#define  FLASHSS_MMC_CORECFG_NO_DDR50		0
#define FLASHSS_MMC_CORECFG_SDR104_SUPPORT		4
#define  FLASHSS_MMC_CORECFG_SDR104			1
#define  FLASHSS_MMC_CORECFG_NO_SDR104		0
#define FLASHSS_MMC_CORECFG_SDR50_SUPPORT		0
#define FLASHSS_MMC_CORECFG_SDR50			1
#define FLASHSS_MMC_CORECFG_NO_SDR5O		0
#define STM_FLASHSS_MMC_CORE_CONFIG_4	\
			  (FLASHSS_MMC_CORECFG_D_DRIVER_SUPPORT	| \
			   FLASHSS_MMC_CORECFG_C_DRIVER_SUPPORT	| \
			   FLASHSS_MMC_CORECFG_A_DRIVER_SUPPORT	| \
			   (FLASHSS_MMC_CORECFG_DDR50 << 8)		| \
			   (FLASHSS_MMC_CORECFG_SDR104 << 4)	| \
			   (FLASHSS_MMC_CORECFG_SDR50 << 0))
#define FLASHSS_MMC_CORE_CONFIG_5			0x410
#define  FLASHSS_MMC_CORECFG_CLOCK_MULTIPLIER	16
#define   CLOCK_MULTIPLIER_NONE		0
#define  FLASHSS_MMC_CORECFG_RETUNING_MODES		12
#define   FLASHSS_MMC_CORECFG_RETUNING_MODE0	0
#define  FLASHSS_MMC_CORECFG_TUNING_FOR_SDR50	8
#define   TUNING_FOR_SDR50		1
#define   TUNING_OFF_SDR50		0
#define  FLASHSS_MMC_CORECFG_RETUNING_TIMER_CNT	0
#define   RETUNING_TIMER_CNT_DISBLE	0
#define   RETUNING_TIMER_CNT_MAX	0xf

#define STM_FLASHSS_MMC_CORE_CONFIG_5	((CLOCK_MULTIPLIER_NONE << 16)	|\
			 (FLASHSS_MMC_CORECFG_RETUNING_MODE0 << 12)	|\
			 (TUNING_FOR_SDR50 << 8)	|\
			 (RETUNING_TIMER_CNT_MAX << 0))

#define FLASHSS_MMC_CORE_CONFIG_6			0x414
#define  FLASHSS_MMC_CORECFG_SPI_BLK_MODE		(1 << 4)
#define  FLASHSS_MMC_CORECFG_SPI_SUPPORT		(1 << 0)
#define FLASHSS_MMC_CORE_CONFIG_7			0x48
#define  FLASHSS_MMC_CORECFG_DSPD_PRESET_VAL	16
#define  FLASHSS_MMC_CORECFG_INIT_PRESETVAL		0
#define FLASHSS_MMC_CORE_CONFIG_8			0x41c
#define  FLASHSS_MMC_CORECFG_SDR12_PRESETVAL	16
#define  FLASHSS_MMC_CORECFG_HSPD_PRESETVAL		0
#define FLASHSS_MMC_CORE_CONFIG_9			0x420
#define  FLASHSS_MMC_CORECFG_SDR50_PRESETVAL	16
#define  FLASHSS_MMC_CORECFG_SDR25_PRESETVAL	0
#define FLASHSS_MMC_CORE_CONFIG_10			0x424
#define  FLASHSS_MMC_CORECFG_DDR50_PRESETVAL	16
#define  FLASHSS_MMC_CORECFG_SDR104_PRESETVAL	0
#define FLASHSS_MMC_CORE_CONFIG_11			0x428
#define  FLASHSS_MMC_CORECFG_MAXCURREN_T1P8V	0
#define FLASHSS_MMC_CORE_CONFIG_12			0x42c
#define  FLASHSS_MMC_CORECFG_MAXCURREN_T3P0V	0
#define FLASHSS_MMC_CORE_CONFIG_13			0x430
#define  FLASHSS_MMC_CORECFG_MAXCURREN_T3P3V
#define FLASHSS_MMC_CORE_TOP_CONFIG			0x440
#define  POWER_DN_CNT_CFG		0
#define FLASHSS_MMC_CORE_GP_OUTPUT			0x450
#define  GP_OUT				30
#define  GP_OUT_0			0
#define STATUS_R			0x60
#endif /* __DRIVERS_STM_STIH407_SDHCI_H */
